# creater_pr.py
"""
Secure PR automation for DevSecOps AI remediation.

Features:
- No shell=True (safe subprocess usage)
- Idempotent PR creation
- Branch collision safe
- Detects no-change scenario
- Supports configurable base branch
- Proper error handling
"""

import subprocess
import sys
import os
from datetime import datetime


BASE_BRANCH = os.getenv("BASE_BRANCH", "main")
BOT_NAME = "devsecops-bot"
BOT_EMAIL = "devsecops-bot@users.noreply.github.com"


def run(cmd: list, check=True, capture=False):
    print(f"[cmd] {' '.join(cmd)}")
    return subprocess.run(
        cmd,
        check=check,
        text=True,
        capture_output=capture
    )


def branch_name():
    ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    return f"devsecops-fixes-{ts}"


def has_changes() -> bool:
    result = run(["git", "status", "--porcelain"], capture=True)
    return bool(result.stdout.strip())


def pr_already_exists(head_branch: str) -> bool:
    try:
        result = run(
            ["gh", "pr", "list", "--head", head_branch, "--json", "number"],
            capture=True
        )
        return bool(result.stdout.strip() and result.stdout != "[]\n")
    except Exception:
        return False


def main():
    try:
        run(["git", "config", "user.name", BOT_NAME])
        run(["git", "config", "user.email", BOT_EMAIL])

        if not has_changes():
            print("No changes detected. Skipping PR creation.")
            return

        new_branch = branch_name()

        run(["git", "checkout", "-b", new_branch])
        run(["git", "add", "."])
        run(["git", "commit", "-m", "chore: apply DevSecOps AI security fixes"])
        run(["git", "push", "origin", new_branch])

        if pr_already_exists(new_branch):
            print("PR already exists for this branch. Skipping creation.")
            return

        run([
            "gh", "pr", "create",
            "--base", BASE_BRANCH,
            "--head", new_branch,
            "--title", "🛡️ DevSecOps: Automated Security Remediations",
            "--body",
            "This PR contains automated security remediations generated by the DevSecOps Agentic AI pipeline.\n\nPlease review before merging."
        ])

        print("PR created successfully.")

    except subprocess.CalledProcessError as e:
        print(f"Error during PR creation: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()