import os
import subprocess
from datetime import datetime

BRANCH = f"devsecops-fixes-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
BASE = "main"
TITLE = "DevSecOps: Automated Security Fixes"
BODY = """
This PR contains **automated security remediations** generated by the
DevSecOps Agentic AI pipeline.

🔍 Please review carefully before merging.
"""

def run(cmd):
    print(f"[cmd] {cmd}")
    subprocess.check_call(cmd, shell=True)

def main():
    run("git config user.name 'devsecops-bot'")
    run("git config user.email 'devsecops-bot@users.noreply.github.com'")

    run(f"git checkout -b {BRANCH}")

    run("git status --porcelain > /tmp/git_changes.txt")
    if not open("/tmp/git_changes.txt").read().strip():
        print("No changes to commit. Skipping PR.")
        return

    run("git add .")
    run("git commit -m 'chore: apply DevSecOps security fixes'")
    run(f"git push origin {BRANCH}")

    run(
        f'gh pr create '
        f'--base {BASE} '
        f'--head {BRANCH} '
        f'--title "{TITLE}" '
        f'--body "{BODY}"'
    )

if __name__ == "__main__":
    main()
