  AI-Gate-Analysis:
    runs-on: ubuntu-latest
    needs: Aggregate-Scanning-Reports
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: pip install -r requirements.txt

      - uses: actions/download-artifact@v4
        with:
          name: all-scan-reports
          path: reports

      - run: mkdir -p agent_output

      - run: |
          python main.py --reports-dir reports --output-dir agent_output --mode=gate --skip-llm

      - name: Debug Gate Output
        run: |
          echo "DEBUG decision.json"
          cat agent_output/decision.json || true
          echo "DEBUG files"
          ls -la agent_output || true

      - uses: actions/upload-artifact@v4
        with:
          name: ai-results
          path: agent_output/

# ============================================================
# SECURITY GATE
# ============================================================
  Security-Gate:
    runs-on: ubuntu-latest
    needs: AI-Gate-Analysis
    outputs:
      gate_failed: ${{ steps.read.outputs.gate_failed }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ai-results
          path: agent_output

      - run: sudo apt-get update && sudo apt-get install -y jq

      - id: read
        run: |
          STATUS=$(jq -r '.decision' agent_output/decision.json)
          echo "DEBUG Gate decision = $STATUS"
          if [ "$STATUS" = "FAIL" ]; then
            echo "gate_failed=true" >> $GITHUB_OUTPUT
          else
            echo "gate_failed=false" >> $GITHUB_OUTPUT
          fi