# ==============================================
# TFSEC REMEDIATION SUGGESTIONS
# Generated by DevSecOps Agentic AI Pipeline
# Review carefully before applying to your .tf files
# ==============================================

# --- Finding 1: AVD-AWS-0124 [LOW] ---
# File: /home/runner/work/Agenytic_autogen_model/Agenytic_autogen_model/terraform/main.tf (lines 5-10)
# Issue: Security group rule does not have a description.
```hcl
# /home/runner/work/Agenytic_autogen_model/Agenytic_autogen_model/terraform/main.tf (line 5)
resource "aws_security_group" "example" {
  name        = "example"
  description = "Example security group"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```
